default:
  paths:
    - "./features/**/*.feature"
  require:
    - "./support/world.js"
    - "./support/hooks.js"
    - "./step-definitions/bookingSteps.js"
  format:
    - "progress-bar"
  timeout: 60000
